import { useEffect, useMemo, useState } from "react";
import {
  ArrowRight, ArrowsClockwise, Brain, CaretDown, ChartLineUp, ChatText, Check, ClipboardText, CloudArrowUp, Database,
  Eye, FileArrowUp, FileText, FolderOpen, Gauge, Info, ListChecks, MagnifyingGlass, Plus, Robot,
  ShieldCheck, Sparkle, SquaresFour, TrendUp, UploadSimple, Warning, X,
} from "@phosphor-icons/react";
import { CartesianGrid, Line, LineChart, RadialBar, RadialBarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, fileToBase64 } from "./api.js";
import { CRITERIA, REASON_TAGS, dateTime, measurement, shortDate, titleCase } from "./constants.js";
import { ConfidentialNote, EmptyState, ErrorState, InfoTip, LoadingState, MetricCard, Modal, PageHeader, StatusBadge } from "./components.jsx";

export const doctorNav = [
  { key: "overview", label: "Overview", icon: SquaresFour },
  { key: "datasets", label: "Datasets", icon: Database },
  { key: "cases", label: "Cases", icon: FolderOpen },
  { key: "workspace", label: "Workspace", icon: ClipboardText },
  { key: "assessments", label: "My Assessments", icon: ListChecks },
];

export function DoctorPortal({ route, routeId, navigate, notify }) {
  if (route === "overview") return <DoctorOverview navigate={navigate} />;
  if (route === "datasets") return <DatasetsPage navigate={navigate} notify={notify} />;
  if (route === "cases") return <CasesPage datasetId={routeId} navigate={navigate} />;
  if (route === "workspace") {
    const [caseId, initialRunId = ""] = routeId.split("~");
    return caseId ? <Workspace caseId={caseId} initialRunId={initialRunId} notify={notify} /> : <WorkspaceLanding navigate={navigate} />;
  }
  if (route === "assessments") return <MyAssessments navigate={navigate} />;
  return <DoctorOverview navigate={navigate} />;
}

function DoctorOverview({ navigate }) {
  const [metrics, setMetrics] = useState(null);
  const [datasets, setDatasets] = useState([]);
  useEffect(() => { Promise.all([api.dashboard(), api.datasets()]).then(([dashboard, data]) => { setMetrics(dashboard.metrics); setDatasets(data.items.slice(0, 3)); }); }, []);
  return <div className="content-page">
    <PageHeader eyebrow="DOCTOR PORTAL" title="Clinical evaluation workspace" copy="Select a longitudinal dataset, inspect a model response and preserve an independent clinical judgement." actions={<button className="primary-button" onClick={() => navigate("datasets")}><CloudArrowUp size={17} />Add dataset</button>} />
    <div className="metrics-grid four"><MetricCard icon={Database} label="Available datasets" value={metrics?.datasets ?? "—"} note="Private and approved shared cohorts" /><MetricCard icon={FolderOpen} label="Available cases" value={metrics?.cases ?? "—"} note="Validated longitudinal records" tone="teal" /><MetricCard icon={Robot} label="Response runs" value={metrics?.runs ?? "—"} note="Runs generated by this account" tone="purple" /><MetricCard icon={ListChecks} label="Submitted reviews" value={metrics?.submitted ?? "—"} note="Editable until final lock" tone="red" /></div>
    <section className="dashboard-grid"><article className="surface dashboard-callout"><span className="callout-icon"><Brain size={27} /></span><div><span className="eyebrow">EVALUATION FLOW</span><h2>From source evidence to an auditable score</h2><p>The model receives visits 1–9. Visit 10 remains withheld as reference evidence for the clinician.</p><div className="flow-steps"><span><b>1</b>Select case</span><span><b>2</b>Generate or choose run</span><span><b>3</b>Score six dimensions</span><span><b>4</b>Submit evidence-linked feedback</span></div></div><button className="secondary-button" onClick={() => navigate("datasets")}>Start evaluation<ArrowRight size={16} /></button></article>
      <article className="surface"><div className="section-heading"><div><span className="eyebrow">RECENT DATASETS</span><h2>Ready for review</h2></div></div><div className="compact-list">{datasets.map((dataset) => <button key={dataset.id} onClick={() => navigate("cases", dataset.id)}><Database size={19} /><span><b>{dataset.name}</b><small>{dataset.validCount} valid · {dataset.quarantinedCount} quarantined</small></span><StatusBadge>{dataset.visibility === "shared" ? "Shared" : dataset.status}</StatusBadge><ArrowRight size={15} /></button>)}</div></article>
    </section>
  </div>;
}

function DatasetsPage({ navigate, notify }) {
  const [items, setItems] = useState([]);
  const [selected, setSelected] = useState(null);
  const [uploadOpen, setUploadOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const refresh = () => api.datasets().then((result) => setItems(result.items)).finally(() => setLoading(false));
  useEffect(() => { refresh(); }, []);
  const inspect = async (id) => { const result = await api.dataset(id); setSelected(result); };
  return <div className="content-page"><PageHeader eyebrow="DATA GOVERNANCE" title="Datasets" copy="Your uploads remain private to you and the administrator. Approved system cohorts are available to every doctor." actions={<button className="primary-button" onClick={() => setUploadOpen(true)}><UploadSimple size={17} />Upload dataset</button>} />
    {loading ? <LoadingState label="Loading datasets…" /> : <section className="surface data-table"><div className="table-head dataset-row"><span>Dataset</span><span>Owner / access</span><span>Quality</span><span>Status</span><span /></div>{items.map((dataset) => <div className="table-row dataset-row" key={dataset.id}><div className="cell-title"><Database size={20} /><span><b>{dataset.name}</b><small>{dataset.sourceFilename}</small></span></div><div><b>{dataset.ownerName}</b><small>{dataset.visibility === "shared" ? "Approved shared cohort" : "Private to uploader + Admin"}</small></div><div><b>{dataset.validCount} valid</b><small>{dataset.quarantinedCount} quarantined · {dataset.declaredCount} declared</small></div><div><StatusBadge>{dataset.status}</StatusBadge></div><div className="row-actions"><button className="text-button" onClick={() => inspect(dataset.id)}><Eye size={15} />Quality</button><button className="secondary-button compact" disabled={!dataset.validCount} onClick={() => navigate("cases", dataset.id)}>Open<ArrowRight size={14} /></button></div></div>)}</section>}
    {uploadOpen && <UploadDatasetModal onClose={() => setUploadOpen(false)} onDone={(result) => { setUploadOpen(false); refresh(); notify(`Dataset imported: ${result.valid} valid, ${result.quarantined} quarantined`); }} />}
    {selected && <DatasetQualityModal data={selected} onClose={() => setSelected(null)} />}
  </div>;
}

function UploadDatasetModal({ onClose, onDone }) {
  const [file, setFile] = useState(null);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const submit = async () => {
    setBusy(true); setError("");
    try { const result = await api.uploadDataset({ fileName: file.name, name: name || file.name.replace(/\.[^.]+$/, ""), description, contentBase64: await fileToBase64(file) }); onDone(result); }
    catch (failure) { setError(failure.message); }
    finally { setBusy(false); }
  };
  return <Modal title="Upload a clinical dataset" copy="Supported formats: Synthea-SG ZIP, standard JSON and the platform CSV template." onClose={onClose} wide><div className="upload-zone"><FileArrowUp size={38} /><h3>{file ? file.name : "Choose a dataset file"}</h3><p>{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB · ready for local validation` : "The original file is retained locally and fingerprinted with SHA-256 for evidence traceability."}</p><label className="secondary-button file-picker">Select ZIP, JSON or CSV<input type="file" accept=".zip,.json,.csv" onChange={(event) => { const next = event.target.files?.[0]; setFile(next); if (next && !name) setName(next.name.replace(/\.[^.]+$/, "")); }} /></label></div><div className="form-grid"><label>Dataset name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Longitudinal chronic-care cohort" /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Purpose, source and limitations…" /></label></div><div className="import-policy"><ShieldCheck size={18} /><span><b>Private by default</b><small>Only you and the administrator can access this upload until Admin shares it.</small></span></div>{error && <div className="form-error"><Warning size={17} />{error}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!file || busy} onClick={submit}>{busy ? <><ArrowsClockwise className="spin" size={16} />Validating and importing…</> : <><UploadSimple size={16} />Import dataset</>}</button></div></Modal>;
}

function DatasetQualityModal({ data, onClose }) {
  const { dataset, issues } = data;
  return <Modal title="Data quality report" copy={`${dataset.name} · SHA-256 ${dataset.sourceSha256.slice(0, 16)}…`} onClose={onClose} wide><div className="quality-metrics"><div><small>Declared</small><strong>{dataset.declaredCount}</strong></div><div className="success"><small>Valid</small><strong>{dataset.validCount}</strong></div><div className="danger"><small>Quarantined</small><strong>{dataset.quarantinedCount}</strong></div><div><small>Schema</small><strong>{dataset.schemaVersion}</strong></div></div><div className="quality-note"><Info size={17} /><p>Missing source records are never reconstructed. They remain in the quarantine report and cannot enter the evaluation workflow.</p></div><div className="issue-list"><div className="issue-header"><b>Validation findings</b><span>{issues.length} displayed</span></div>{issues.slice(0, 80).map((issue) => <div key={issue.id}><StatusBadge tone={issue.severity === "critical" || issue.severity === "high" ? "danger" : "warning"}>{issue.severity}</StatusBadge><span><b>{issue.patientId || "Dataset"}</b><small>{issue.message}</small></span><code>{issue.code}</code></div>)}</div></Modal>;
}

function CasesPage({ datasetId, navigate }) {
  const [datasets, setDatasets] = useState([]);
  const [selectedId, setSelectedId] = useState(datasetId || "");
  const [cases, setCases] = useState([]);
  const [total, setTotal] = useState(0);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.datasets().then((result) => { setDatasets(result.items); if (!selectedId && result.items[0]) setSelectedId(result.items[0].id); }); }, []);
  useEffect(() => { if (!selectedId) return; setLoading(true); const timer = window.setTimeout(() => api.cases(selectedId, { search }).then((result) => { setCases(result.items); setTotal(result.total); }).finally(() => setLoading(false)), 180); return () => window.clearTimeout(timer); }, [selectedId, search]);
  return <div className="content-page"><PageHeader eyebrow="CASE LIBRARY" title="Validated longitudinal cases" copy="Choose a patient record. Every visible case passed structural validation and retains its original evidence." actions={<select className="dataset-select" value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.name}</option>)}</select>} />
    <div className="list-toolbar"><label><MagnifyingGlass size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search patient ID or condition" /></label><span>{total} eligible cases</span></div>{loading ? <LoadingState label="Loading validated cases…" /> : <section className="surface data-table"><div className="table-head case-row"><span>Patient</span><span>Longitudinal context</span><span>Demographics</span><span>Evidence</span><span /></div>{cases.map((item) => <button className="table-row case-row clickable" key={item.id} onClick={() => navigate("workspace", item.id)}><div className="cell-title"><span className="patient-avatar">{item.patientId.slice(-2)}</span><span><b>{item.patientId}</b><small>Synthetic patient</small></span></div><div><b>{item.condition}</b><small>{item.visits} completed visits</small></div><div><b>{item.age || "—"} years · {titleCase(item.sex)}</b><small>{titleCase(item.ethnicity)}</small></div><div><StatusBadge>Validated</StatusBadge><small>SHA {item.sourceSha256.slice(0, 8)}…</small></div><ArrowRight size={16} /></button>)}</section>}
  </div>;
}

function WorkspaceLanding({ navigate }) {
  return <EmptyState icon={ClipboardText} title="Select a case to open the workspace" copy="Choose a validated longitudinal patient from the case library." action={<button className="primary-button" onClick={() => navigate("cases")}>Browse cases<ArrowRight size={16} /></button>} />;
}

function Workspace({ caseId, initialRunId, notify }) {
  const [caseData, setCaseData] = useState(null);
  const [runs, setRuns] = useState([]);
  const [selectedRunId, setSelectedRunId] = useState("");
  const [assessment, setAssessment] = useState(null);
  const [draft, setDraft] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [evidenceOpen, setEvidenceOpen] = useState(false);

  const refreshRuns = async (preferId) => { const result = await api.runs(caseId); setRuns(result.items); const next = preferId || selectedRunId || result.items.find((item) => item.status === "Completed")?.id || ""; setSelectedRunId(next); return next; };
  useEffect(() => { setLoading(true); Promise.all([api.case(caseId), api.runs(caseId)]).then(([caseResult, runResult]) => { setCaseData(caseResult.case); setRuns(runResult.items); setSelectedRunId(runResult.items.find((item) => item.id === initialRunId && item.status === "Completed")?.id || runResult.items.find((item) => item.status === "Completed")?.id || ""); }).catch((failure) => setError(failure.message)).finally(() => setLoading(false)); }, [caseId, initialRunId]);
  useEffect(() => { if (!selectedRunId) { setAssessment(null); setDraft(null); return; } api.assessment(selectedRunId).then((result) => { const value = result.assessment; setAssessment(value); setDraft(buildDraft(value)); }); }, [selectedRunId]);
  const selectedRun = runs.find((item) => item.id === selectedRunId);
  const generate = async () => { setGenerating(true); setError(""); try { const run = await api.generateRun(caseId); await refreshRuns(run.id); notify(`New ${run.provider} response saved`); } catch (failure) { setError(failure.message); } finally { setGenerating(false); } };
  const save = async (status) => { if (!draft) return; setSaving(true); setError(""); try { const result = await api.saveAssessment(selectedRunId, { ...draft, status, criteria: CRITERIA.map((criterion) => ({ key: criterion.key, ...draft.criteria[criterion.key] })) }); setAssessment(result.assessment); setDraft(buildDraft(result.assessment)); notify(status === "Submitted" ? "Assessment submitted and remains editable until Admin locks it" : "Draft saved to SQLite"); } catch (failure) { setError(failure.message); } finally { setSaving(false); } };
  if (loading) return <LoadingState />;
  if (error && !caseData) return <ErrorState message={error} />;
  const visits = caseData?.clinicalData?.visits || [];
  return <div className="workspace-shell"><div className="workflow-bar"><span className="complete"><b>1</b><i>Case context<small>Visits 1–9 + withheld reference</small></i></span><span className={selectedRun ? "complete" : "active"}><b>2</b><i>AI response<small>Choose or generate a run</small></i></span><span className={selectedRun ? "active" : ""}><b>3</b><i>Evaluation<small>Score and explain</small></i></span><span className={assessment?.status === "Submitted" ? "complete" : ""}><b>4</b><i>Submit<small>Editable until final lock</small></i></span></div>
    <div className="workspace-grid"><section className="workspace-column patient-column"><div className="column-heading"><span>SIMULATED PATIENT DATA</span><button className="text-button" onClick={() => setEvidenceOpen(true)}><Eye size={14} />Raw evidence</button></div><PatientContext patient={caseData} visits={visits} /></section>
      <section className="workspace-column response-column"><div className="column-heading"><span>AI RESPONSE · VISIT 10 PLAN</span><div className="run-controls"><select value={selectedRunId} onChange={(event) => setSelectedRunId(event.target.value)}><option value="">Select a response run</option>{runs.map((run) => <option key={run.id} value={run.id}>{run.status} · {run.modelVersion} · {shortDate(run.createdAt)}</option>)}</select><button className="secondary-button compact" disabled={generating} onClick={generate}>{generating ? <ArrowsClockwise className="spin" size={14} /> : <Plus size={14} />}{generating ? "Generating…" : "New run"}</button></div></div>{error && <div className="inline-alert"><Warning size={16} />{error}</div>}{selectedRun ? <ResponsePanel run={selectedRun} /> : <EmptyState icon={Robot} title="No response selected" copy="Generate a new DeepSeek response or choose an existing run. Every run is versioned independently." action={<button className="primary-button" disabled={generating} onClick={generate}>{generating ? "Generating with DeepSeek…" : "Generate response"}</button>} />}</section>
      <section className="workspace-column review-column"><div className="column-heading"><span>SAFETY REVIEW COCKPIT</span><InfoTip>Scores are private from other doctors.</InfoTip></div>{selectedRun && draft ? <ReviewCockpit draft={draft} setDraft={setDraft} assessment={assessment} saving={saving} onSave={save} /> : <EmptyState icon={Gauge} title="Choose a response run" copy="The rubric opens after a completed AI response is selected." />}</section></div>
    {evidenceOpen && <RawEvidenceModal patient={caseData} onClose={() => setEvidenceOpen(false)} />}
  </div>;
}

function buildDraft(assessment) {
  const criteria = Object.fromEntries(CRITERIA.map((item) => { const existing = assessment?.criteria?.find((score) => score.key === item.key); return [item.key, existing || { score: null, feedback: "", tags: [], customTags: [] }]; }));
  return { criteria, safetyIssue: assessment?.safetyIssue || "Undecided", reasonTags: assessment?.reasonTags || [], caseFeedback: assessment?.caseFeedback || "" };
}

function PatientContext({ patient, visits }) {
  const chartData = visits.map((visit) => ({ date: shortDate(visit.date).replace(/ \d{4}$/, ""), sbp: measurement(visit, "systolic_bp"), hba1c: measurement(visit, "hba1c"), egfr: measurement(visit, "egfr"), ldl: measurement(visit, "ldl_cholesterol") }));
  const latest = visits.at(-1) || {};
  return <div className="patient-scroll"><article className="patient-summary"><header className="patient-summary-head"><div className="patient-identity"><span className="patient-avatar large">{patient.patientId.slice(-2)}</span><div><span className="summary-kicker">PATIENT RECORD</span><h2>{patient.patientId}</h2><p>{patient.age || "—"}-year-old · {titleCase(patient.sex)} · {titleCase(patient.ethnicity)}</p></div></div><StatusBadge>Synthetic</StatusBadge></header><dl className="patient-meta-strip"><div><dt>Dataset</dt><dd title={patient.datasetName}>{patient.datasetName}</dd></div><div><dt>Reference visit</dt><dd>{shortDate(latest.date)}</dd></div><div><dt>History</dt><dd>{visits.length} longitudinal visits</dd></div></dl><div className="diagnosis-block"><div className="diagnosis-heading"><b>Active conditions</b><span>{patient.conditions.length}</span></div><ul>{patient.conditions.map((condition) => <li key={condition.key || condition.display}>{condition.display || titleCase(condition.key)}</li>)}</ul></div></article>
    <article className="timeline-card"><div className="subsection-title"><b>Clinical timeline</b><span>{visits.length} visits</span></div><div className="timeline">{visits.map((visit, index) => <div key={`${visit.visit_number}-${visit.date}`} className={index === visits.length - 1 ? "reference" : ""}><i /><span><b>{shortDate(visit.date)}</b><small>Visit {visit.visit_number}{index === visits.length - 1 ? " · Reference" : " · Model input"}</small></span><p>{visit.consultation?.reason_for_consultation?.type ? titleCase(visit.consultation.reason_for_consultation.type) : "Chronic-care review"}</p></div>)}</div></article>
    <article className="trend-card"><div className="subsection-title"><b>Longitudinal trends</b><span>Source measurements</span></div><div className="trend-chart"><ResponsiveContainer width="100%" height={180}><LineChart data={chartData} margin={{ top: 8, right: 8, left: -25, bottom: 0 }}><CartesianGrid stroke="#edf1f5" vertical={false} /><XAxis dataKey="date" tick={{ fontSize: 9, fill: "#728198" }} /><YAxis tick={{ fontSize: 9, fill: "#728198" }} /><Tooltip /><Line type="monotone" dataKey="sbp" name="SBP" stroke="#c8102e" strokeWidth={2} dot={false} connectNulls /><Line type="monotone" dataKey="egfr" name="eGFR" stroke="#087a5b" strokeWidth={2} dot={false} connectNulls /></LineChart></ResponsiveContainer></div><div className="trend-legend"><span className="red">SBP</span><span className="green">eGFR</span><small>Additional labs remain available in raw evidence.</small></div></article>
    <p className="source-note">Source: synthetic research dataset · SHA {patient.sourceSha256.slice(0, 16)}…</p></div>;
}

function ResponsePanel({ run }) {
  const lines = String(run.output || "").split("\n");
  return <div className="response-scroll"><div className="response-meta"><span><Robot size={17} /><b>{run.provider}</b><small>{run.modelVersion}</small></span><span><FileText size={17} /><b>{run.promptVersion}</b><small>{dateTime(run.completedAt)}</small></span><StatusBadge>{run.status}</StatusBadge></div><article className="model-output">{lines.map((line, index) => line.startsWith("### ") ? <h3 key={index}>{renderInlineMarkdown(line.slice(4))}</h3> : line.startsWith("## ") ? <h2 key={index}>{renderInlineMarkdown(line.slice(3))}</h2> : /^\d+\./.test(line.trim()) ? <p className="numbered" key={index}>{renderInlineMarkdown(line)}</p> : line.trim().startsWith("-") ? <p className="bullet" key={index}>{renderInlineMarkdown(line.replace(/^\s*-\s*/, ""))}</p> : line.trim() ? <p key={index}>{renderInlineMarkdown(line)}</p> : null)}</article><div className="evidence-callout"><ShieldCheck size={19} /><div><b>Reference visit remains withheld</b><p>This response was generated from visits 1–9 only. Visit 10 is available to the doctor as reference evidence.</p></div></div></div>;
}

function renderInlineMarkdown(text) {
  return String(text).split(/(\*\*[^*]+\*\*)/g).filter(Boolean).map((part, index) => part.startsWith("**") && part.endsWith("**") ? <strong key={`${part}-${index}`}>{part.slice(2, -2)}</strong> : part);
}

function ReviewCockpit({ draft, setDraft, assessment, saving, onSave }) {
  const [customInputs, setCustomInputs] = useState({});
  const [expandedFeedback, setExpandedFeedback] = useState(() => new Set(CRITERIA.filter((criterion) => { const value = draft.criteria[criterion.key]; return value.feedback || value.tags.length || value.customTags.length; }).map((criterion) => criterion.key)));
  const scores = CRITERIA.map((criterion) => draft.criteria[criterion.key].score).filter(Boolean);
  const overall = scores.length ? scores.reduce((sum, score) => sum + score, 0) / scores.length : 0;
  const updateCriterion = (key, changes) => setDraft((current) => ({ ...current, criteria: { ...current.criteria, [key]: { ...current.criteria[key], ...changes } } }));
  const allScored = scores.length === CRITERIA.length;
  const locked = assessment?.locked;
  const toggleFeedback = (key) => setExpandedFeedback((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; });
  return <div className="review-scroll"><div className="overall-score"><div className="score-ring"><ResponsiveContainer width="100%" height="100%"><RadialBarChart innerRadius="76%" outerRadius="100%" data={[{ value: overall * 20, fill: "#c8102e" }]} startAngle={90} endAngle={-270}><RadialBar dataKey="value" cornerRadius={3} background={{ fill: "#e9eef3" }} /></RadialBarChart></ResponsiveContainer><strong>{overall ? overall.toFixed(1) : "—"}<small>/5</small></strong></div><div><span>OVERALL ASSESSMENT</span><h2>{overall >= 4 ? "Good" : overall >= 3 ? "Moderate" : overall ? "Needs attention" : "Not scored"}</h2><p>{scores.length} of {CRITERIA.length} dimensions completed.</p></div>{locked && <StatusBadge tone="danger">Locked</StatusBadge>}</div>
    <div className="rubric-intro"><b>Clinical rubric</b><span>1 = Poor · 5 = Excellent</span></div><div className="criteria-list">{CRITERIA.map((criterion, index) => { const value = draft.criteria[criterion.key]; const isOpen = expandedFeedback.has(criterion.key); const feedbackCount = value.tags.length + value.customTags.length + (value.feedback.trim() ? 1 : 0); return <article className={`criterion-card${isOpen ? " feedback-open" : ""}`} key={criterion.key}><div className="criterion-title"><span>{index + 1}</span><div><b>{criterion.label}</b><small>{criterion.description}</small></div><InfoTip>Feedback is optional and visible only to Admin.</InfoTip></div><div className="score-buttons" role="radiogroup" aria-label={criterion.label}>{[1, 2, 3, 4, 5].map((score) => <button disabled={locked} key={score} aria-checked={value.score === score} role="radio" className={value.score === score ? "selected" : ""} onClick={() => updateCriterion(criterion.key, { score })}>{score}</button>)}</div><button type="button" className="criterion-feedback-toggle" aria-expanded={isOpen} onClick={() => toggleFeedback(criterion.key)}><ChatText size={13} /><span>{feedbackCount ? `${feedbackCount} feedback item${feedbackCount > 1 ? "s" : ""}` : "Add optional feedback"}</span><CaretDown className={isOpen ? "open" : ""} size={13} /></button>{isOpen && <div className="criterion-feedback"><div className="feedback-tags">{criterion.tags.map((tag) => <button disabled={locked} key={tag} className={value.tags.includes(tag) ? "selected" : ""} onClick={() => updateCriterion(criterion.key, { tags: value.tags.includes(tag) ? value.tags.filter((item) => item !== tag) : [...value.tags, tag] })}>{value.tags.includes(tag) && <Check size={11} />}{tag}</button>)}{value.customTags.map((tag) => <button disabled={locked} className="selected custom" key={tag} onClick={() => updateCriterion(criterion.key, { customTags: value.customTags.filter((item) => item !== tag) })}>{tag}<X size={11} /></button>)}</div><div className="custom-tag-row"><input disabled={locked} value={customInputs[criterion.key] || ""} onChange={(event) => setCustomInputs({ ...customInputs, [criterion.key]: event.target.value })} onKeyDown={(event) => { if (event.key === "Enter" && event.currentTarget.value.trim()) { event.preventDefault(); const tag = event.currentTarget.value.trim(); updateCriterion(criterion.key, { customTags: [...new Set([...value.customTags, tag])] }); setCustomInputs({ ...customInputs, [criterion.key]: "" }); } }} placeholder="Add a custom tag and press Enter" /></div><textarea disabled={locked} value={value.feedback} onChange={(event) => updateCriterion(criterion.key, { feedback: event.target.value })} placeholder={`Optional feedback on ${criterion.label.toLowerCase()}…`} /></div>}</article>; })}</div>
    <section className="review-section"><b>Safety-critical check</b><span>Any unsafe or potentially harmful recommendations?</span><div className="binary-choice">{["Yes", "No", "Undecided"].map((value) => <button disabled={locked} className={draft.safetyIssue === value ? "selected" : ""} key={value} onClick={() => setDraft({ ...draft, safetyIssue: value })}>{value}</button>)}</div></section>
    <section className="review-section"><b>Missing / needs clarification</b><span>Select all that apply.</span><div className="feedback-tags">{REASON_TAGS.map((tag) => <button disabled={locked} className={draft.reasonTags.includes(tag) ? "selected" : ""} key={tag} onClick={() => setDraft({ ...draft, reasonTags: draft.reasonTags.includes(tag) ? draft.reasonTags.filter((item) => item !== tag) : [...draft.reasonTags, tag] })}>{tag}</button>)}</div></section>
    <label className="case-feedback"><b>Overall case feedback <small>(optional)</small></b><textarea disabled={locked} value={draft.caseFeedback} onChange={(event) => setDraft({ ...draft, caseFeedback: event.target.value })} placeholder="Summarise the most important concern or strength…" /></label>
    <div className="review-actions"><button className="secondary-button" disabled={!allScored || saving || locked} onClick={() => onSave("Draft")}>Save draft</button><button className="primary-button" disabled={!allScored || saving || locked} onClick={() => onSave("Submitted")}>{saving ? "Saving…" : assessment?.status === "Submitted" ? "Update submitted assessment" : "Submit assessment"}</button></div><ConfidentialNote>{locked ? "Included in a finalized Admin result; editing is disabled." : "Your scoring is not visible to other doctors and remains editable until Admin finalizes it."}</ConfidentialNote></div>;
}

function RawEvidenceModal({ patient, onClose }) {
  const [visit, setVisit] = useState(patient.clinicalData.visits.length);
  const selected = patient.clinicalData.visits[visit - 1];
  return <Modal title="Original evidence trace" copy={`${patient.sourceEntry} · SHA-256 ${patient.sourceSha256}`} onClose={onClose} wide><div className="evidence-toolbar"><label>Visit<select value={visit} onChange={(event) => setVisit(Number(event.target.value))}>{patient.clinicalData.visits.map((item) => <option key={item.visit_number} value={item.visit_number}>Visit {item.visit_number} · {shortDate(item.date)}</option>)}</select></label><span><b>JSON Path</b><code>$.visits[{visit - 1}]</code></span><StatusBadge>{visit === patient.clinicalData.visits.length ? "Reference visit" : "Model input"}</StatusBadge></div><pre className="json-viewer">{JSON.stringify(selected, null, 2)}</pre></Modal>;
}

function MyAssessments({ navigate }) {
  const [items, setItems] = useState(null);
  useEffect(() => { api.assessments().then((result) => setItems(result.items)); }, []);
  return <div className="content-page"><PageHeader eyebrow="MY JUDGEMENTS" title="Assessment history" copy="Submitted assessments remain editable until the administrator finalizes a result that includes them." />{!items ? <LoadingState label="Loading assessment history…" /> : items.length ? <section className="surface data-table"><div className="table-head assessment-row"><span>Case / model run</span><span>Dataset</span><span>Score</span><span>Status</span><span>Updated</span><span /></div>{items.map((item) => <div className="table-row assessment-row" key={item.id}><div><b>{item.patientId}</b><small>{item.modelVersion} · {item.runId.slice(-8)}</small></div><div><b>{item.datasetName}</b><small>{item.criteria.length} dimensions</small></div><strong className="table-score">{item.overallScore?.toFixed(1) || "—"}</strong><div><StatusBadge>{item.locked ? "Locked" : item.status}</StatusBadge></div><span>{dateTime(item.updatedAt)}</span><button className="secondary-button compact" onClick={() => navigate("workspace", `${item.caseId}~${item.runId}`)}>{item.locked ? "View" : "Edit"}</button></div>)}</section> : <EmptyState icon={ListChecks} title="No assessments yet" copy="Open a case and evaluate a completed model response." />}</div>;
}
